### ISSUE TITLE
order of compiled rulesets not defined

### ISSUE THREAD

**Issue by kwaegema** [UtrechtUniversity/irods-ruleset-research#1]
Hi,
Trying to debug some issue, we found that compiled rulesets are not in the same order on each node. This makes it difficult to diff the rulesets, and could possibly give different execution results (?). Is it possible to order the source files (in the correct but deterministic order) after the find here : https://github.com/UtrechtUniversity/irods-ruleset-research/blob/00b31c0757657ad80af266e9164f6f9504480996/Makefile#L29
This is also the case with the other irods-ruleset libraries.

Thanks!

**Comment by lwesterhof** [comment]
Thanks!
